// src/utils/permisosMap.js
// Enum de nombres de permisos (sin IDs, solo nombres estables)

export const ADMIN_PERM_NAME = 'USUARIO_ADMIN';

export const PERMISOS = Object.freeze({
  USUARIO_ADMIN: 'USUARIO_ADMIN',

  INCIDENCIA_LEER: 'INCIDENCIA_LEER',
  INCIDENCIA_CREAR: 'INCIDENCIA_CREAR',
  INCIDENCIA_EDITAR: 'INCIDENCIA_EDITAR',
  INCIDENCIA_BORRAR: 'INCIDENCIA_BORRAR',

  RESOLUCION_LEER: 'RESOLUCION_LEER',
  RESOLUCION_CREAR: 'RESOLUCION_CREAR',
  RESOLUCION_EDITAR: 'RESOLUCION_EDITAR',
  RESOLUCION_BORRAR: 'RESOLUCION_BORRAR',

  CONTRATO_LEER: 'CONTRATO_LEER',
  CONTRATO_CREAR: 'CONTRATO_CREAR',
  CONTRATO_EDITAR: 'CONTRATO_EDITAR',
  CONTRATO_BORRAR: 'CONTRATO_BORRAR',
  CONTRATO_DETALLE_IMPRESION_LEER: 'CONTRATO_DETALLE_IMPRESION_LEER',
  CONTRATO_DETALLE_IMPRESION_EDITAR: 'CONTRATO_DETALLE_IMPRESION_EDITAR',

  ACTIVO_LEER: 'ACTIVO_LEER',
  ACTIVO_CREAR: 'ACTIVO_CREAR',
  ACTIVO_EDITAR: 'ACTIVO_EDITAR',
  ACTIVO_BORRAR: 'ACTIVO_BORRAR',

  SERVICIO_LEER: 'SERVICIO_LEER',
  SERVICIO_CREAR: 'SERVICIO_CREAR',
  SERVICIO_EDITAR: 'SERVICIO_EDITAR',
  SERVICIO_BORRAR: 'SERVICIO_BORRAR',

  DISPOSITIVO_LEER: 'DISPOSITIVO_LEER',
  DISPOSITIVO_CREAR: 'DISPOSITIVO_CREAR',
  DISPOSITIVO_EDITAR: 'DISPOSITIVO_EDITAR',
  DISPOSITIVO_BORRAR: 'DISPOSITIVO_BORRAR',

  OTROSDISPOSITIVO_LEER: 'OTROSDISPOSITIVO_LEER',
  OTROSDISPOSITIVO_CREAR: 'OTROSDISPOSITIVO_CREAR',
  OTROSDISPOSITIVO_EDITAR: 'OTROSDISPOSITIVO_EDITAR',
  OTROSDISPOSITIVO_BORRAR: 'OTROSDISPOSITIVO_BORRAR',

  CONSUMIBLE_LEER: 'CONSUMIBLE_LEER',
  CONSUMIBLE_CREAR: 'CONSUMIBLE_CREAR',
  CONSUMIBLE_EDITAR: 'CONSUMIBLE_EDITAR',
  CONSUMIBLE_BORRAR: 'CONSUMIBLE_BORRAR',

  CONSUMO_LEER: 'CONSUMO_LEER',
  CONSUMO_CREAR: 'CONSUMO_CREAR',
  CONSUMO_EDITAR: 'CONSUMO_EDITAR',
  CONSUMO_BORRAR: 'CONSUMO_BORRAR',

  CATEGORIA_LEER: 'CATEGORIA_LEER',
  CATEGORIA_CREAR: 'CATEGORIA_CREAR',
  CATEGORIA_EDITAR: 'CATEGORIA_EDITAR',
  CATEGORIA_BORRAR: 'CATEGORIA_BORRAR',

  MODELO_LEER: 'MODELO_LEER',
  MODELO_CREAR: 'MODELO_CREAR',
  MODELO_EDITAR: 'MODELO_EDITAR',
  MODELO_BORRAR: 'MODELO_BORRAR',

  MARCA_LEER: 'MARCA_LEER',
  MARCA_CREAR: 'MARCA_CREAR',
  MARCA_EDITAR: 'MARCA_EDITAR',
  MARCA_BORRAR: 'MARCA_BORRAR',

  PROVEEDOR_LEER: 'PROVEEDOR_LEER',
  PROVEEDOR_CREAR: 'PROVEEDOR_CREAR',
  PROVEEDOR_EDITAR: 'PROVEEDOR_EDITAR',
  PROVEEDOR_BORRAR: 'PROVEEDOR_BORRAR',

  PERMISO_LEER: 'PERMISO_LEER',
  PERMISO_CREAR: 'PERMISO_CREAR',
  PERMISO_EDITAR: 'PERMISO_EDITAR',
  PERMISO_BORRAR: 'PERMISO_BORRAR',
  PERMISOS_ASIGNAR: 'PERMISOS_ASIGNAR',

  SITIO_LEER: 'SITIO_LEER',
  SITIO_CREAR: 'SITIO_CREAR',
  SITIO_EDITAR: 'SITIO_EDITAR',
  SITIO_BORRAR: 'SITIO_BORRAR',

  UBICACION_LEER: 'UBICACION_LEER',
  UBICACION_CREAR: 'UBICACION_CREAR',
  UBICACION_EDITAR: 'UBICACION_EDITAR',
  UBICACION_BORRAR: 'UBICACION_BORRAR',

  PARAMETROAMBIENTE_LEER: 'PARAMETROAMBIENTE_LEER',
  PARAMETROAMBIENTE_CREAR: 'PARAMETROAMBIENTE_CREAR',
  PARAMETROAMBIENTE_EDITAR: 'PARAMETROAMBIENTE_EDITAR',
  PARAMETROAMBIENTE_BORRAR: 'PARAMETROAMBIENTE_BORRAR',

  USUARIO_LEER: 'USUARIO_LEER',
  USUARIO_CREAR: 'USUARIO_CREAR',
  USUARIO_EDITAR: 'USUARIO_EDITAR',
  USUARIO_BORRAR: 'USUARIO_BORRAR',

  USUARIOPERMISO_LEER: 'USUARIOPERMISO_LEER',
  USUARIOPERMISO_EDITAR: 'USUARIOPERMISO_EDITAR',
  USUARIOPERMISO_BORRAR: 'USUARIOPERMISO_BORRAR',

  TIPOPERMISO_LEER: 'TIPO_LEER',
  TIPOPERMISO_CREAR: 'TIPO_CREAR',
  TIPOPERMISO_EDITAR: 'TIPO_EDITAR',
  TIPOPERMISO_BORRAR: 'TIPO_BORRAR',

  AUDITORIA_VER: 'AUDITORIA_VER',

});
